# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e6f043db-9169-4aa4-a231-fbdbc92642d2";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" "noatime" "ssd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e6f043db-9169-4aa4-a231-fbdbc92642d2";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:5" "noatime" "ssd" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/e6f043db-9169-4aa4-a231-fbdbc92642d2";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:7" "noatime" "ssd" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/e6f043db-9169-4aa4-a231-fbdbc92642d2";
      fsType = "btrfs";
      options = [ "subvol=@cache" "compress=zstd:1" "noatime" "ssd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4543-6113";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e6f043db-9169-4aa4-a231-fbdbc92642d2";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:4" "noatime" "ssd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d3d4f685-36d8-4d26-ba90-91eddc792dbd"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
