# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8256d3d8-6b23-4a7c-b547-38909baf022f";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6090-C5F4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c40248c7-c845-46e9-807f-a855387f78b6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
